# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299a5dc0bb90a00eefa4bb728aa0dbe384745d59764be4e55c828eed4f9d1987b62c1901d8ca1281ef73dba2e6ca73bbdf84b1a856d0c5c64d3ebd2e8c18ce2a

test:
  secret_key_base: 6c3c455162b301295f771b42e63d6b8bf6e25f403161dc94dc6f9ca6729aa1ffa63d1f55f64d6cf02fecbcb6cc8ebfe80896cd199edc668e916b4f7216843db2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
